name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve

  approve-destroy:
    name: Approve Destroy
    runs-on: ubuntu-latest
    needs: terraform
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Request approval
        id: approval
        run: |
          echo "waiting for approval"
          while [ ! -f /tmp/approved ]; do
            echo "approval pending..."
            sleep 60
          done
          echo "approval received"

      - name: Notify approval
        if: always()
        run: echo "Proceeding with Terraform destroy..."

  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    needs: approve-destroy
    if: github.event_name == 'workflow_dispatch'

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: infra-nimbux
        run: terraform init

      - name: Terraform Destroy
        working-directory: infra-nimbux
        run: terraform destroy -auto-approve
